name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  update-dependencies:
    name: Update dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Upgrade packages
        run: npm up
      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "build(deps): update dependencies (automated)"
          branch: "build-deps-update-automated"
          commit-message: "build(deps): update dependencies (automated)"
